### ISSUE TITLE
Decide which tool we write the report in

### ISSUE THREAD

**Issue by amatzen** [amatzen/SE04-SE-G09-SPRO#13]
Candidates:
- LaTeX
- Markdown
- Notion
- Google Docs
- Microsoft Word
- Handwritten
- OpenOffice Writer

**Comment by amatzen** [comment]
Can all group members confirm that we chose LaTeX using Overleaf last Friday? @Ashvikan @Berkanktk @danielbahrami @esbendamkjaer @jasanfarah

**Comment by Berkanktk** [comment]
نعم أستطيع

**Comment by Berkanktk** [comment]
很遗憾

**Comment by amatzen** [comment]
كانت جيدة بركان
