### ISSUE TITLE
Research about the props for the map

### ISSUE THREAD

**Issue by esbendamkjaer** [amatzen/SE04-SE-G09-SPRO#5]
- [x] Find potential asset sets, that we can use for our game
- [x] Research how we can draw these assets using LibGDX
- [x] Develop a conceptual demo, that can potentially be used as inspiration for how this will be implemented in the final game.

**Comment by Berkanktk** [comment]
Modern city
- https://www.kenney.nl/assets/roguelike-modern-city

Racing pack
- https://www.kenney.nl/assets/racing-pack

Vehicles
- https://www.kenney.nl/assets/pixel-vehicle-pack

Other assets
- https://www.kenney.nl/assets/pixel-platformer

UI development toolkit
- https://github.com/UnderwaterApps/overlap2d
- See video [here](https://www.youtube.com/watch?v=I0g-t0nZ-qE)

**Comment by Berkanktk** [comment]
Procedural generation is gonna be tough
may we all get through this well enough
this libgdx thing is such a pain in the assy
development this semester will be nasty.

Amen

**Comment by jasanfarah** [comment]
amin
